from turtle import *

a = Screen()
a.bgcolor("#80ffff")
b = Turtle()
b.shape("turtle")
b.pensize("5")
b.color("Green")
b.write("     Hi, all programmers!")
b.penup()
b.left(90)
b.forward(120)
b.pendown()
b.circle(100)
b.penup()
b.forward(100)
b.pendown()
b.circle(50)
b.penup()
b.forward(-250)
b.color("Black")
b.write("   Hello, boss, I am little turtle :)  ", move=True, font=('Arial', 18, 'bold'))
b.color("Green")
b.penup()
b.goto(-100,120)
b.tilt(30)

a.mainloop()
