@startuml

interface RenewDriverLicense
RenewDriverLicense : +renew()
RenewDriverLicense <|.. Person
Person : #name:String
Person : -ssn:String
Person : ~age:int
Person : +driverLicense:String
Person <|-- Employee
Employee <|-- Manager
Employee : +doTask()
Manager : +assignTask()
Person <|-- Student
Person <|-- Teacher
Student : +doHomework()
Teacher : +assignHomework()
@enduml