@startuml 

skinparam class {
    BackgroundColor LightBlue
    ArrowColor #FF00FF
    BorderColor DarkBlue
}

Person "is" <|-- Student
Person "is" <|-- Teacher
Person "is" <|-- Employee
Employee "is" <|-- Manager
Person : name:String
Person : SSN:String
Person : gender:Char
Person : age:int
Person : toString()
Employee : employeeID:String
Student : doHomework()
Teacher : assignHomework()
Teacher : classes:ArrayList
Student : studentID:String

@enduml